In [1]:
import torch

In [2]:
#scalar
scalar=torch.tensor(5)
scalar

tensor(5)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
#To convert the tensor into a python integer (Only works with scalars(one element tesors))
scalar.item()

5

In [6]:
# Vectors are one dimensional tensors but can contain multiple numbers
#Vector
vector=torch.tensor([64,53])
vector

tensor([64, 53])

In [7]:
vector.ndim

1

In [8]:
#Shape of a vector tells us how to elemenst inside a vecotr are arranged
vector.shape

torch.Size([2])

It gives two because you put two numbers into the vector.

In [9]:
# Matrices are vectors with TWO dimensions.
MATRIX=torch.tensor([[73,75732],[47,228]])
MATRIX

tensor([[   73, 75732],
        [   47,   228]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
ex0=torch.tensor([1,3,5,2,5])
ex0

tensor([1, 3, 5, 2, 5])

In [13]:
ex0.ndim

1

In [14]:
ex0.shape

torch.Size([5])

In [15]:
ex=torch.tensor([[2,4],
                 [3,5],
                 [7,1]])
ex

tensor([[2, 4],
        [3, 5],
        [7, 1]])

In [16]:
ex.ndim

2

In [17]:
ex.shape

torch.Size([3, 2])

In [18]:
ex2=torch.tensor([[2,8],[4,1],[75,49],[719,38]])
ex2

tensor([[  2,   8],
        [  4,   1],
        [ 75,  49],
        [719,  38]])

In [19]:
ex2.ndim

2

In [20]:
ex2.shape

torch.Size([4, 2])

In [21]:
ex3=torch.tensor([[3,5,1,5,2],[4,1,48,6,6],[29,653,5,32,6]])
ex3

tensor([[  3,   5,   1,   5,   2],
        [  4,   1,  48,   6,   6],
        [ 29, 653,   5,  32,   6]])

In [22]:
ex3.ndim

2

In [23]:
ex3.shape

torch.Size([3, 5])

In [24]:
ex4=torch.rand(2,4,5)
ex4

tensor([[[0.6929, 0.7619, 0.8812, 0.1728, 0.7774],
         [0.1881, 0.8344, 0.2487, 0.1713, 0.0635],
         [0.8207, 0.0427, 0.4943, 0.6729, 0.1494],
         [0.9979, 0.5296, 0.1641, 0.2162, 0.8707]],

        [[0.9711, 0.8039, 0.5501, 0.8385, 0.4529],
         [0.8605, 0.9396, 0.1137, 0.6444, 0.1301],
         [0.5181, 0.2647, 0.0880, 0.2270, 0.6046],
         [0.1972, 0.4333, 0.7171, 0.9073, 0.4942]]])

In [25]:
ex4.ndim

3

In [26]:
ex4.shape

torch.Size([2, 4, 5])

In [27]:
ex5=torch.rand(4,3,2)
ex5

tensor([[[0.7789, 0.1682],
         [0.0094, 0.2445],
         [0.8911, 0.8321]],

        [[0.1200, 0.3260],
         [0.3457, 0.2957],
         [0.4098, 0.7482]],

        [[0.3866, 0.8168],
         [0.4305, 0.2413],
         [0.8641, 0.3003]],

        [[0.0059, 0.5729],
         [0.3734, 0.2545],
         [0.6897, 0.0118]]])

In [28]:
ex5.ndim

3

In [29]:
ex.shape

torch.Size([3, 2])

In [30]:
ex6=torch.rand(2,4,3,5)
ex6

tensor([[[[0.9931, 0.1168, 0.6716, 0.1681, 0.4354],
          [0.5095, 0.5501, 0.7275, 0.0465, 0.7774],
          [0.4128, 0.4399, 0.2902, 0.0855, 0.0089]],

         [[0.1425, 0.3474, 0.4017, 0.3200, 0.7337],
          [0.9222, 0.8889, 0.0237, 0.6372, 0.7848],
          [0.7411, 0.3156, 0.3671, 0.3514, 0.2942]],

         [[0.4480, 0.2421, 0.8844, 0.7294, 0.2559],
          [0.3428, 0.3152, 0.7915, 0.2410, 0.8635],
          [0.3690, 0.6569, 0.6382, 0.9779, 0.8057]],

         [[0.1643, 0.5866, 0.4884, 0.3975, 0.0647],
          [0.2299, 0.9929, 0.2179, 0.5184, 0.9253],
          [0.0221, 0.1830, 0.4195, 0.6929, 0.5759]]],


        [[[0.9516, 0.1911, 0.7478, 0.5186, 0.0919],
          [0.9706, 0.1871, 0.0041, 0.0241, 0.3407],
          [0.3150, 0.0383, 0.3816, 0.4461, 0.0336]],

         [[0.3946, 0.5747, 0.8072, 0.5822, 0.2242],
          [0.5933, 0.1112, 0.2253, 0.3920, 0.7162],
          [0.0453, 0.3017, 0.8724, 0.9880, 0.8047]],

         [[0.2868, 0.9855, 0.8950, 0.5879, 0.9848]

In [31]:
ex6.ndim

4

In [32]:
ex6.shape

torch.Size([2, 4, 3, 5])

## Probably, ndim gives the number of dimensions and shape gives us the dimensions of the tensor(or matrix) in the form of $n$x$m$x$...$.

In [33]:
TENSOR=torch.tensor([[[473,478,37],
                      [273,472,72],
                      [72819,47,281]]])
TENSOR

tensor([[[  473,   478,    37],
         [  273,   472,    72],
         [72819,    47,   281]]])

In [34]:
TENSOR.ndim

3

In [35]:
TENSOR.shape

torch.Size([1, 3, 3])

In [36]:
TENSOR2=torch.tensor([[[2,3,73],[27,73,21],
                      [27,65,36],[10,738,98],
                      [472,73,63],[73,482,63]],[[2,3,73],[27,73,21],
                      [27,65,36],[10,738,98],
                      [472,73,63],[73,482,63]]])
TENSOR2

tensor([[[  2,   3,  73],
         [ 27,  73,  21],
         [ 27,  65,  36],
         [ 10, 738,  98],
         [472,  73,  63],
         [ 73, 482,  63]],

        [[  2,   3,  73],
         [ 27,  73,  21],
         [ 27,  65,  36],
         [ 10, 738,  98],
         [472,  73,  63],
         [ 73, 482,  63]]])

In [37]:
TENSOR2.ndim

3

In [38]:
TENSOR2.shape

torch.Size([2, 6, 3])

By Convention, we use all caps for tensors and matrices and lower case for vectors and scalars. There are no terms as scalars, vectors, matrices in the syntax. All of them are tensors. The shape and dimensions of the tensor define the term used.

To Summarize

| Name | What is it? | Number of dimensions | Lower or upper (usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | a single number | 0 | Lower (`a`) | 
| **vector** | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (`y`) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (`Q`) |
| **tensor** | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (`X`) | 


In [39]:
# Random tensors
rand_ten= torch.rand(size=(5,3))
rand_ten,rand_ten.dtype

(tensor([[0.9307, 0.2047, 0.9102],
         [0.7537, 0.7382, 0.4093],
         [0.8215, 0.6938, 0.3436],
         [0.6726, 0.6349, 0.0772],
         [0.1314, 0.2939, 0.3545]]),
 torch.float32)

In [40]:
rand_ten.dtype

torch.float32

For Example, if we want to create a tensor for the common image shape  of (224, 224, 3) ie, (Height, Width, Color Channels).

In [41]:
rand_image=torch.rand(size=(3,224,224))
rand_image

tensor([[[0.7235, 0.3475, 0.1128,  ..., 0.7870, 0.7319, 0.6244],
         [0.9130, 0.7502, 0.0262,  ..., 0.5601, 0.3764, 0.1332],
         [0.0326, 0.0666, 0.0381,  ..., 0.5440, 0.0450, 0.7834],
         ...,
         [0.3312, 0.3437, 0.1137,  ..., 0.1090, 0.7219, 0.3526],
         [0.7155, 0.0402, 0.0209,  ..., 0.2060, 0.9748, 0.8547],
         [0.4337, 0.9035, 0.8697,  ..., 0.0928, 0.6882, 0.6823]],

        [[0.3749, 0.1274, 0.0679,  ..., 0.9208, 0.5695, 0.1757],
         [0.6695, 0.3983, 0.9633,  ..., 0.1439, 0.8342, 0.6253],
         [0.7849, 0.3406, 0.0078,  ..., 0.8696, 0.3369, 0.3489],
         ...,
         [0.9902, 0.3673, 0.7743,  ..., 0.1442, 0.0641, 0.2402],
         [0.9773, 0.6198, 0.4050,  ..., 0.0056, 0.1235, 0.4614],
         [0.1538, 0.6105, 0.3765,  ..., 0.9220, 0.4059, 0.7821]],

        [[0.9005, 0.4082, 0.3391,  ..., 0.3896, 0.9649, 0.3884],
         [0.1506, 0.6456, 0.9188,  ..., 0.2503, 0.1541, 0.5787],
         [0.9122, 0.1805, 0.5534,  ..., 0.4106, 0.3451, 0.

In [42]:
rand_image.ndim

3

In [43]:
rand_image.shape

torch.Size([3, 224, 224])

To create a tensor with just aeros (used to mask values which we dont need the model to learn)

In [44]:
zeros=torch.zeros(size=(5,4))

In [45]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [46]:
zeros.dtype

torch.float32

In [47]:
ones=torch.ones(size=(5,4))

In [48]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [49]:
ones.dtype

torch.float32

In [50]:
zero_ten=torch.arange(start=0,end=10,step=1)
zero_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
zero_ten_three=torch.arange(start=0,end=10,step=3)
zero_ten_three

tensor([0, 3, 6, 9])

To create a tensor with same shape as another :

In [52]:
ten_ones=torch.ones_like(input=zero_ten_three)
ten_ones

tensor([1, 1, 1, 1])

In [53]:
tensor_float_32=torch.tensor([3.0,6.0,1.0],
                            dtype=None)
tensor_float_32

tensor([3., 6., 1.])

In [54]:
tensor_float_32.dtype

torch.float32

In [55]:
tensor_float_32.ndim

1

In [56]:
tensor_float_32.shape

torch.Size([3])

In [57]:
tensor_float_32.device

device(type='cpu')

In [58]:
tensor_float_16=torch.tensor([3.0,6.0,10.2],
                            dtype=torch.float16)
tensor_float_16

tensor([ 3.0000,  6.0000, 10.2031], dtype=torch.float16)

# Why are there discrepensies with the precision digit after the decimal point?

It is because of float16 is less precise than float32 so due to the roundoff error there r slight dicrepancies but since it takes less space, its used in places where memory is a scarce resource.

In [59]:
tensor_float_16.dtype

torch.float16

In [60]:
some_tensor=torch.rand(5,4)
some_tensor

tensor([[0.0316, 0.7063, 0.1055, 0.7054],
        [0.5167, 0.1111, 0.8219, 0.5887],
        [0.8636, 0.1042, 0.0918, 0.9745],
        [0.4481, 0.7971, 0.5347, 0.9317],
        [0.7867, 0.1356, 0.0354, 0.8421]])

In [61]:
some_tensor.dtype

torch.float32

In [62]:
some_tensor.device

device(type='cpu')

In [63]:
some_tensor.shape

torch.Size([5, 4])

In [64]:
print(f"Shape of tensor : {some_tensor.shape}")

Shape of tensor : torch.Size([5, 4])


In [65]:
print(f"Data Type of tensor : {some_tensor.dtype}")

Data Type of tensor : torch.float32


In [66]:
print(f"Device of tensor : {some_tensor.device}")

Device of tensor : cpu


### Tensor Operations

In [67]:
tens=torch.tensor([4,2,8])
tens+10

tensor([14, 12, 18])

In [68]:
tens

tensor([4, 2, 8])

In [69]:
tens*10

tensor([40, 20, 80])

In [70]:
tens

tensor([4, 2, 8])

In [71]:
tens-10

tensor([-6, -8, -2])

In [72]:
tens=tens-10
tens

tensor([-6, -8, -2])

In [73]:
torch.mul(tens,10)

tensor([-60, -80, -20])

In [74]:
tens

tensor([-6, -8, -2])

In [75]:
torch.add(tens,10)

tensor([4, 2, 8])

In [76]:
torch.sub(tens,10)

tensor([-16, -18, -12])

In [77]:
torch.div(tens,10)

tensor([-0.6000, -0.8000, -0.2000])

In [78]:
tens

tensor([-6, -8, -2])

In [79]:
tens/10

tensor([-0.6000, -0.8000, -0.2000])

In [80]:
tens

tensor([-6, -8, -2])

In [81]:
tens=tens/10

In [82]:
tens

tensor([-0.6000, -0.8000, -0.2000])

In [83]:
tens.dtype

torch.float32

In [84]:
tens=torch.tensor([3,5,9])
tens

tensor([3, 5, 9])

Element wise multiplicaton:

In [85]:
tens * tens

tensor([ 9, 25, 81])

### Matrix Mult

For Matrix Mult, there are two rules to it :
* Inner dimensions should match
    ex : (3,2) @ (2,5) Works but 
         (2,5) @ (3,7) Doesn't
* The resulting matrix should take the outer dimensions

Note: "@" in Python is the symbol for matrix multiplication.

In [86]:
tens=torch.tensor([1,4,8])
tens.shape

torch.Size([3])

In [87]:
tens*tens

tensor([ 1, 16, 64])

In [88]:
tens.matmul(tens)

tensor(81)

In [89]:
torch.matmul(tens,tens)

tensor(81)

In [90]:
tens@tens

tensor(81)

We can do matrix mult more primitively by setting up 'for' loops but it is very computationally expensive and shdnt be done unless we hv a better algorithm than matmul.

In [91]:
%%time
matmul=0
for i in range(len(tens)):
    matmul+=tens[i]*tens[i]
matmul

CPU times: user 353 µs, sys: 0 ns, total: 353 µs
Wall time: 240 µs


tensor(81)

In [92]:
%%time
tens.matmul(tens)

CPU times: user 107 µs, sys: 19 µs, total: 126 µs
Wall time: 89.9 µs


tensor(81)

In [93]:
%%time
torch.matmul(tens,tens)

CPU times: user 115 µs, sys: 21 µs, total: 136 µs
Wall time: 97.5 µs


tensor(81)

In [94]:
tens_a=torch.tensor([[2,6],
                    [3,6],
                    [1,7]])
tens_b=torch.tensor([[48,82],
                    [72,83],
                    [24,57]])

In [95]:
tens_a.shape, tens_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [96]:
tens_a*tens_b

tensor([[ 96, 492],
        [216, 498],
        [ 24, 399]])

In [97]:
# matmul(tens_a,tens_b)
# This wont run coz the shapes r 3*2 and 3*2

We can make it work by transposing either of the matrices

* torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
* tensor.T - where tensor is the desired tensor to transpose.

In [98]:
tens_a


tensor([[2, 6],
        [3, 6],
        [1, 7]])

In [99]:
tens_b

tensor([[48, 82],
        [72, 83],
        [24, 57]])

In [100]:
tens_b.T

tensor([[48, 72, 24],
        [82, 83, 57]])

In [101]:
torch.matmul(tens_a,tens_b.T)

tensor([[588, 642, 390],
        [636, 714, 414],
        [622, 653, 423]])

In [102]:
tens_a.matmul(tens_b.T)

tensor([[588, 642, 390],
        [636, 714, 414],
        [622, 653, 423]])

In [103]:
tens_a.mm(tens_b.T)

tensor([[588, 642, 390],
        [636, 714, 414],
        [622, 653, 423]])

In [104]:
torch.mm(tens_a,tens_b.T)

tensor([[588, 642, 390],
        [636, 714, 414],
        [622, 653, 423]])

The torch.nn.Linear() module also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.

$$y = x \cdot A^\intercal + b$$

x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).

A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the T, that's because the weights matrix gets transposed).
Note: You might also often see W or another letter like X used to showcase the weights matrix.

b is the bias term used to slightly offset the weights and inputs.

y is the output (a manipulation of the input in the hopes to discover patterns in it).


In [105]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = torch.rand(3,2)
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 1.0348,  0.4592,  0.3892,  0.0690,  0.3858,  0.3514],
        [ 0.9272,  0.3378,  0.3622, -0.0094,  0.4842,  0.3286],
        [ 1.1711,  0.5868,  0.4136,  0.1433,  0.2987,  0.3971]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


### Agregation

In [106]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [107]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


`print(f"Mean: {x.mean()}")`  will error  
Mean won't work without the float datatype :  
`print(f"Mean: {x.type(torch.float32).mean()}")`

In [108]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [109]:
x.max(),x.min()

(tensor(90), tensor(0))

In [110]:
x.type(torch.float32).mean()

tensor(45.)

We can also use `torch.max()` , `torch.min()` etc

In [111]:
torch.max(x), torch.min(x)

(tensor(90), tensor(0))

We can use `argmax(.)`,`argmin(.)` to find the index of the max or min value

In [112]:
torch.argmax(x), torch.argmin(x)

(tensor(9), tensor(0))

### Changing Datatype of a tensor

To change the data type of a tensor we use `type(type.__)`

In [113]:
tens=torch.arange(1,100,10)
tens,tens.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [114]:
tens_float32=tens.type(torch.float32)
tens_float32,tens_float32.dtype

(tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.]), torch.float32)

In [115]:
tens_int64=tens_float32.type(torch.int64)
tens_int64,tens_int64.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

### Reshaping, Stacking, Squeezing, Unsqueezing

#### Reshape

In [116]:
x=torch.arange(1,8)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

In [117]:
x.reshape(1,7)

tensor([[1, 2, 3, 4, 5, 6, 7]])

In [118]:
x.reshape(7,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]])

In [119]:
x.reshape(1,1,7)

tensor([[[1, 2, 3, 4, 5, 6, 7]]])

In [120]:
x.reshape(7,1,1)

tensor([[[1]],

        [[2]],

        [[3]],

        [[4]],

        [[5]],

        [[6]],

        [[7]]])

In [121]:
tens=torch.randint(low=0, high=25, size=(2,3,4))
tens,tens.shape

(tensor([[[24, 13, 16, 19],
          [12, 19, 22,  5],
          [ 0,  4,  8, 14]],
 
         [[14,  1,  7, 10],
          [11, 22,  2, 19],
          [ 7, 23, 18, 19]]]),
 torch.Size([2, 3, 4]))

In [122]:
tens.reshape(2,3,1,4)

tensor([[[[24, 13, 16, 19]],

         [[12, 19, 22,  5]],

         [[ 0,  4,  8, 14]]],


        [[[14,  1,  7, 10]],

         [[11, 22,  2, 19]],

         [[ 7, 23, 18, 19]]]])

In [123]:
tens.reshape(2,12)

tensor([[24, 13, 16, 19, 12, 19, 22,  5,  0,  4,  8, 14],
        [14,  1,  7, 10, 11, 22,  2, 19,  7, 23, 18, 19]])

In [124]:
tens.reshape(4,2,3)

tensor([[[24, 13, 16],
         [19, 12, 19]],

        [[22,  5,  0],
         [ 4,  8, 14]],

        [[14,  1,  7],
         [10, 11, 22]],

        [[ 2, 19,  7],
         [23, 18, 19]]])

In [125]:
tens.reshape(4,3,2)

tensor([[[24, 13],
         [16, 19],
         [12, 19]],

        [[22,  5],
         [ 0,  4],
         [ 8, 14]],

        [[14,  1],
         [ 7, 10],
         [11, 22]],

        [[ 2, 19],
         [ 7, 23],
         [18, 19]]])

In [126]:
tens.reshape(6,4)

tensor([[24, 13, 16, 19],
        [12, 19, 22,  5],
        [ 0,  4,  8, 14],
        [14,  1,  7, 10],
        [11, 22,  2, 19],
        [ 7, 23, 18, 19]])

In [127]:
tens.reshape(8,3)

tensor([[24, 13, 16],
        [19, 12, 19],
        [22,  5,  0],
        [ 4,  8, 14],
        [14,  1,  7],
        [10, 11, 22],
        [ 2, 19,  7],
        [23, 18, 19]])

#### View

In [128]:
z=tens

In [129]:
x=z.view(2,12)
x

tensor([[24, 13, 16, 19, 12, 19, 22,  5,  0,  4,  8, 14],
        [14,  1,  7, 10, 11, 22,  2, 19,  7, 23, 18, 19]])

In [130]:
y=z.reshape(2,12)
y

tensor([[24, 13, 16, 19, 12, 19, 22,  5,  0,  4,  8, 14],
        [14,  1,  7, 10, 11, 22,  2, 19,  7, 23, 18, 19]])

In [131]:
z[:,0]=5
z

tensor([[[ 5,  5,  5,  5],
         [12, 19, 22,  5],
         [ 0,  4,  8, 14]],

        [[ 5,  5,  5,  5],
         [11, 22,  2, 19],
         [ 7, 23, 18, 19]]])

In [132]:
x

tensor([[ 5,  5,  5,  5, 12, 19, 22,  5,  0,  4,  8, 14],
        [ 5,  5,  5,  5, 11, 22,  2, 19,  7, 23, 18, 19]])

In [133]:
y

tensor([[ 5,  5,  5,  5, 12, 19, 22,  5,  0,  4,  8, 14],
        [ 5,  5,  5,  5, 11, 22,  2, 19,  7, 23, 18, 19]])

Even when we change the viewed and reshaped tensors both the viewed and reshaped tensor change the original tensor.

In [134]:
x[0,0]=6969
x

tensor([[6969,    5,    5,    5,   12,   19,   22,    5,    0,    4,    8,   14],
        [   5,    5,    5,    5,   11,   22,    2,   19,    7,   23,   18,   19]])

In [135]:
z

tensor([[[6969,    5,    5,    5],
         [  12,   19,   22,    5],
         [   0,    4,    8,   14]],

        [[   5,    5,    5,    5],
         [  11,   22,    2,   19],
         [   7,   23,   18,   19]]])

In [136]:
y

tensor([[6969,    5,    5,    5,   12,   19,   22,    5,    0,    4,    8,   14],
        [   5,    5,    5,    5,   11,   22,    2,   19,    7,   23,   18,   19]])

In [137]:
y[0,0]=10
y

tensor([[10,  5,  5,  5, 12, 19, 22,  5,  0,  4,  8, 14],
        [ 5,  5,  5,  5, 11, 22,  2, 19,  7, 23, 18, 19]])

In [138]:
z

tensor([[[10,  5,  5,  5],
         [12, 19, 22,  5],
         [ 0,  4,  8, 14]],

        [[ 5,  5,  5,  5],
         [11, 22,  2, 19],
         [ 7, 23, 18, 19]]])

This is because both view and reshape share the underlying data with teh original tensor so making changes in any will reflect on the other.

#### Squeeze / Unsqueeze

`squeeze()` returns a tensor with all the dimensions of size 1 removed. Unsqueeze adds a dimension of size 1 inserted at the specified position.

In [139]:
tens,tens.shape

(tensor([[[10,  5,  5,  5],
          [12, 19, 22,  5],
          [ 0,  4,  8, 14]],
 
         [[ 5,  5,  5,  5],
          [11, 22,  2, 19],
          [ 7, 23, 18, 19]]]),
 torch.Size([2, 3, 4]))

In [140]:
tens.squeeze()

tensor([[[10,  5,  5,  5],
         [12, 19, 22,  5],
         [ 0,  4,  8, 14]],

        [[ 5,  5,  5,  5],
         [11, 22,  2, 19],
         [ 7, 23, 18, 19]]])

When theres no size 1 dimension, squeeze returns the original tensor

In [141]:
ex1=torch.arange(1,26).reshape(5,1,5)
ex1,ex1.shape

(tensor([[[ 1,  2,  3,  4,  5]],
 
         [[ 6,  7,  8,  9, 10]],
 
         [[11, 12, 13, 14, 15]],
 
         [[16, 17, 18, 19, 20]],
 
         [[21, 22, 23, 24, 25]]]),
 torch.Size([5, 1, 5]))

In [142]:
ex1.squeeze(), ex1.squeeze().shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25]]),
 torch.Size([5, 5]))

In [143]:
ex1, ex1.shape

(tensor([[[ 1,  2,  3,  4,  5]],
 
         [[ 6,  7,  8,  9, 10]],
 
         [[11, 12, 13, 14, 15]],
 
         [[16, 17, 18, 19, 20]],
 
         [[21, 22, 23, 24, 25]]]),
 torch.Size([5, 1, 5]))

In [144]:
ex1.unsqueeze(0), ex1.unsqueeze(0).shape

(tensor([[[[ 1,  2,  3,  4,  5]],
 
          [[ 6,  7,  8,  9, 10]],
 
          [[11, 12, 13, 14, 15]],
 
          [[16, 17, 18, 19, 20]],
 
          [[21, 22, 23, 24, 25]]]]),
 torch.Size([1, 5, 1, 5]))

In [145]:
ex1.unsqueeze(1), ex1.unsqueeze(1).shape

(tensor([[[[ 1,  2,  3,  4,  5]]],
 
 
         [[[ 6,  7,  8,  9, 10]]],
 
 
         [[[11, 12, 13, 14, 15]]],
 
 
         [[[16, 17, 18, 19, 20]]],
 
 
         [[[21, 22, 23, 24, 25]]]]),
 torch.Size([5, 1, 1, 5]))

In [146]:
ex1.squeeze().unsqueeze(0), ex1.squeeze().unsqueeze(0).shape

(tensor([[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20],
          [21, 22, 23, 24, 25]]]),
 torch.Size([1, 5, 5]))

In [147]:
ex1.squeeze().unsqueeze(1),ex1.squeeze().unsqueeze(1).shape

(tensor([[[ 1,  2,  3,  4,  5]],
 
         [[ 6,  7,  8,  9, 10]],
 
         [[11, 12, 13, 14, 15]],
 
         [[16, 17, 18, 19, 20]],
 
         [[21, 22, 23, 24, 25]]]),
 torch.Size([5, 1, 5]))

In [148]:
ex1, ex1.shape

(tensor([[[ 1,  2,  3,  4,  5]],
 
         [[ 6,  7,  8,  9, 10]],
 
         [[11, 12, 13, 14, 15]],
 
         [[16, 17, 18, 19, 20]],
 
         [[21, 22, 23, 24, 25]]]),
 torch.Size([5, 1, 5]))

In [149]:
ex1.unsqueeze(2),ex1.unsqueeze(2).shape

(tensor([[[[ 1,  2,  3,  4,  5]]],
 
 
         [[[ 6,  7,  8,  9, 10]]],
 
 
         [[[11, 12, 13, 14, 15]]],
 
 
         [[[16, 17, 18, 19, 20]]],
 
 
         [[[21, 22, 23, 24, 25]]]]),
 torch.Size([5, 1, 1, 5]))

In [150]:
ex1.unsqueeze(3),ex1.unsqueeze(3).shape

(tensor([[[[ 1],
           [ 2],
           [ 3],
           [ 4],
           [ 5]]],
 
 
         [[[ 6],
           [ 7],
           [ 8],
           [ 9],
           [10]]],
 
 
         [[[11],
           [12],
           [13],
           [14],
           [15]]],
 
 
         [[[16],
           [17],
           [18],
           [19],
           [20]]],
 
 
         [[[21],
           [22],
           [23],
           [24],
           [25]]]]),
 torch.Size([5, 1, 5, 1]))

`ex1.unsqueeze(4),ex1.unsqueeze(4).shape` gives error dimension out of range.

#### Permute

`permute()` gives us a **view** by rearranging the dimensions of the input tensor according to the indices provided as arguments. 

In [151]:
tens=torch.arange(1,25).reshape(2,3,4)
tens

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [152]:
tens.permute(2,0,1), tens.permute(2,0,1).shape

(tensor([[[ 1,  5,  9],
          [13, 17, 21]],
 
         [[ 2,  6, 10],
          [14, 18, 22]],
 
         [[ 3,  7, 11],
          [15, 19, 23]],
 
         [[ 4,  8, 12],
          [16, 20, 24]]]),
 torch.Size([4, 2, 3]))

### Indexing

In [153]:
tens=torch.arange(1,33).reshape(2,4,4)
tens,tens.shape

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]],
 
         [[17, 18, 19, 20],
          [21, 22, 23, 24],
          [25, 26, 27, 28],
          [29, 30, 31, 32]]]),
 torch.Size([2, 4, 4]))

In [154]:
# Checking out some doubts about 1D tensors
tens=torch.randn(1)
tens,tens.shape,tens.ndim

x=tens.unsqueeze(1)
tens.unsqueeze(1),tens.unsqueeze(1).shape,tens.unsqueeze(1).ndim

x.unsqueeze(1)
x.unsqueeze(1),x.unsqueeze(1).shape, x.unsqueeze(1).ndim

(tensor([[[0.2815]]]), torch.Size([1, 1, 1]), 3)

In [155]:
tens, tens[0]

(tensor([0.2815]), tensor(0.2815))

In [156]:
tens=torch.arange(1,181).reshape(3,2,5,6)
tens,tens.shape

(tensor([[[[  1,   2,   3,   4,   5,   6],
           [  7,   8,   9,  10,  11,  12],
           [ 13,  14,  15,  16,  17,  18],
           [ 19,  20,  21,  22,  23,  24],
           [ 25,  26,  27,  28,  29,  30]],
 
          [[ 31,  32,  33,  34,  35,  36],
           [ 37,  38,  39,  40,  41,  42],
           [ 43,  44,  45,  46,  47,  48],
           [ 49,  50,  51,  52,  53,  54],
           [ 55,  56,  57,  58,  59,  60]]],
 
 
         [[[ 61,  62,  63,  64,  65,  66],
           [ 67,  68,  69,  70,  71,  72],
           [ 73,  74,  75,  76,  77,  78],
           [ 79,  80,  81,  82,  83,  84],
           [ 85,  86,  87,  88,  89,  90]],
 
          [[ 91,  92,  93,  94,  95,  96],
           [ 97,  98,  99, 100, 101, 102],
           [103, 104, 105, 106, 107, 108],
           [109, 110, 111, 112, 113, 114],
           [115, 116, 117, 118, 119, 120]]],
 
 
         [[[121, 122, 123, 124, 125, 126],
           [127, 128, 129, 130, 131, 132],
           [133, 134, 135, 136, 137,

In [157]:
tens[0]

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29, 30]],

        [[31, 32, 33, 34, 35, 36],
         [37, 38, 39, 40, 41, 42],
         [43, 44, 45, 46, 47, 48],
         [49, 50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59, 60]]])

`[0]` gives us the first $n-1$ order tensor where $n$ is the ndim of the input tensor.

In [158]:
tens[0][0]

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]])

`[0]` gives us the first $n-2$ order tensor where $n$ is the ndim of the input tensor.

In [159]:
tens[0][0][0]

tensor([1, 2, 3, 4, 5, 6])

`[0]` gives us the first $n-3$ order tensor where $n$ is the ndim of the input tensor.

In [160]:
tens[0][0][0][0]

tensor(1)

`[0]` gives us the first $n-4$ order tensor where $n$ is the ndim of the input tensor.

* So in general, `[0]`$^m$ gives us the first $n-m$ tensor where n is the ndim of the input tensor and m is the number of times theres `[0]`.

In [161]:
tens[2][1]

tensor([[151, 152, 153, 154, 155, 156],
        [157, 158, 159, 160, 161, 162],
        [163, 164, 165, 166, 167, 168],
        [169, 170, 171, 172, 173, 174],
        [175, 176, 177, 178, 179, 180]])

In [162]:
tens[2:,1]

tensor([[[151, 152, 153, 154, 155, 156],
         [157, 158, 159, 160, 161, 162],
         [163, 164, 165, 166, 167, 168],
         [169, 170, 171, 172, 173, 174],
         [175, 176, 177, 178, 179, 180]]])

In [163]:
tens, tens.shape

(tensor([[[[  1,   2,   3,   4,   5,   6],
           [  7,   8,   9,  10,  11,  12],
           [ 13,  14,  15,  16,  17,  18],
           [ 19,  20,  21,  22,  23,  24],
           [ 25,  26,  27,  28,  29,  30]],
 
          [[ 31,  32,  33,  34,  35,  36],
           [ 37,  38,  39,  40,  41,  42],
           [ 43,  44,  45,  46,  47,  48],
           [ 49,  50,  51,  52,  53,  54],
           [ 55,  56,  57,  58,  59,  60]]],
 
 
         [[[ 61,  62,  63,  64,  65,  66],
           [ 67,  68,  69,  70,  71,  72],
           [ 73,  74,  75,  76,  77,  78],
           [ 79,  80,  81,  82,  83,  84],
           [ 85,  86,  87,  88,  89,  90]],
 
          [[ 91,  92,  93,  94,  95,  96],
           [ 97,  98,  99, 100, 101, 102],
           [103, 104, 105, 106, 107, 108],
           [109, 110, 111, 112, 113, 114],
           [115, 116, 117, 118, 119, 120]]],
 
 
         [[[121, 122, 123, 124, 125, 126],
           [127, 128, 129, 130, 131, 132],
           [133, 134, 135, 136, 137,

In [164]:
tens[:,:,4,:]

tensor([[[ 25,  26,  27,  28,  29,  30],
         [ 55,  56,  57,  58,  59,  60]],

        [[ 85,  86,  87,  88,  89,  90],
         [115, 116, 117, 118, 119, 120]],

        [[145, 146, 147, 148, 149, 150],
         [175, 176, 177, 178, 179, 180]]])

Here, the the 5th (index=4) row of each sub tensor with dim $5$X$6$ is selected.

## The data explorer's motto : **VISUALIZE, VISUALIZE, VISUALIZE**

### PyTorch and NumPy

PyTorch and NumPy have fucntionality to interact pretty nicely.

To convert NumPy arrays to Pytorch tensors and vice-versa:
 * `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor. 
 * `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

From an array to a tensor :

In [165]:
import numpy as np
arr=np.arange(1,10)
tens=torch.from_numpy(arr)
arr, tens

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

The default datatype for NumPy is `float64` so when we convert a NumPy array to a PyTorch tensor it retains the `float64` datatype. But many PyTorch calculations default to `float32`.      
So to convert a NumPy array(`float64`) to a PyTorch tensor(`float64`) to a Pytorch tensor(`float32`) we do `tensor = torch.from_numpy(array).type(torch.float32)`

In [166]:
arr.dtype, tens.dtype

(dtype('int64'), torch.int64)

In [167]:
tens=torch.from_numpy(arr).type(torch.float32)
tens.dtype

torch.float32

From a tensor to an array :

In [168]:
numpy_tens=tens.numpy()
tens,numpy_tens

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32))

In [169]:
tens.dtype, numpy_tens.dtype

(torch.float32, dtype('float32'))

**For both tensors and arrays converted from each other when we change any one theres no change in the other**

In [170]:
numpy_tens+1,tens

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [171]:
numpy_tens+1==tens

False

In [172]:
arr+1,tens

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [173]:
arr+1==tens

False

### Reproducibility

To get the same random tensors to make the code reproducable, we use seeds and `torch.manual_seed(seed)`.

In [174]:
torch.manual_seed(seed=42)
rand1=torch.rand(2,3,4)
rand3=torch.rand(3,4,5)
rand1,rand3

(tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
          [0.3904, 0.6009, 0.2566, 0.7936],
          [0.9408, 0.1332, 0.9346, 0.5936]],
 
         [[0.8694, 0.5677, 0.7411, 0.4294],
          [0.8854, 0.5739, 0.2666, 0.6274],
          [0.2696, 0.4414, 0.2969, 0.8317]]]),
 tensor([[[0.1053, 0.2695, 0.3588, 0.1994, 0.5472],
          [0.0062, 0.9516, 0.0753, 0.8860, 0.5832],
          [0.3376, 0.8090, 0.5779, 0.9040, 0.5547],
          [0.3423, 0.6343, 0.3644, 0.7104, 0.9464]],
 
         [[0.7890, 0.2814, 0.7886, 0.5895, 0.7539],
          [0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
          [0.6440, 0.7071, 0.6581, 0.4913, 0.8913],
          [0.1447, 0.5315, 0.1587, 0.6542, 0.3278]],
 
         [[0.6532, 0.3958, 0.9147, 0.2036, 0.2018],
          [0.2018, 0.9497, 0.6666, 0.9811, 0.0874],
          [0.0041, 0.1088, 0.1637, 0.7025, 0.6790],
          [0.9155, 0.2418, 0.1591, 0.7653, 0.2979]]]))

In [175]:
torch.manual_seed(seed=42)
rand2=torch.rand(2,3,4)
rand4=torch.rand(3,4,5)
rand2,rand4

(tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
          [0.3904, 0.6009, 0.2566, 0.7936],
          [0.9408, 0.1332, 0.9346, 0.5936]],
 
         [[0.8694, 0.5677, 0.7411, 0.4294],
          [0.8854, 0.5739, 0.2666, 0.6274],
          [0.2696, 0.4414, 0.2969, 0.8317]]]),
 tensor([[[0.1053, 0.2695, 0.3588, 0.1994, 0.5472],
          [0.0062, 0.9516, 0.0753, 0.8860, 0.5832],
          [0.3376, 0.8090, 0.5779, 0.9040, 0.5547],
          [0.3423, 0.6343, 0.3644, 0.7104, 0.9464]],
 
         [[0.7890, 0.2814, 0.7886, 0.5895, 0.7539],
          [0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
          [0.6440, 0.7071, 0.6581, 0.4913, 0.8913],
          [0.1447, 0.5315, 0.1587, 0.6542, 0.3278]],
 
         [[0.6532, 0.3958, 0.9147, 0.2036, 0.2018],
          [0.2018, 0.9497, 0.6666, 0.9811, 0.0874],
          [0.0041, 0.1088, 0.1637, 0.7025, 0.6790],
          [0.9155, 0.2418, 0.1591, 0.7653, 0.2979]]]))

We need to reset the seed every time to get the same random tensors each time.
Each seed gives the same rand tensors on same number of calls.

In [176]:
torch.manual_seed(seed=1)
rando=torch.rand(2,3,4)
rando

tensor([[[0.7576, 0.2793, 0.4031, 0.7347],
         [0.0293, 0.7999, 0.3971, 0.7544],
         [0.5695, 0.4388, 0.6387, 0.5247]],

        [[0.6826, 0.3051, 0.4635, 0.4550],
         [0.5725, 0.4980, 0.9371, 0.6556],
         [0.3138, 0.1980, 0.4162, 0.2843]]])

Changing the seed changes the random tensors or the flavour of the randomness.
All randomness in a computer is pseudo-randomness since a computer itself is a deterministic machine but some theories disagree.

## GPU

In [177]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [178]:
torch.cuda.is_available()

True

In [179]:
device="cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [ ]:
tens=torch.rand(2,3)
tens_gpu=tens.to(device)
tens_gpu